version: '3'

services:
  mongo:
    container_name: ${PROJECT_NAME}_mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: on-failure
    volumes:
      - ./.docker/mongo:/data/db
    ports:
      - "${MONGO_PORT}:27017"

