version: '3.2'

services:
  mongo:
    container_name: ${PROJECT_NAME}_mongo
    image: mongo
    restart: on-failure
    volumes:
      - ./.docker/mongo:/data/db
    ports:
      - "${MONGO_PORT}:27017"

